name: 'Directory re-creator'
description: |
  USE WITH CAUTION!
  This action removes and re-creates a directory including all files and sub-directories within.
  If no directory is specified, the github.workspace directroy will be used.
author: 'Chris Aurora Neumann Ruud (based on Peder Schmedling)'
inputs:
  directory:
    description: 'The directory to remove and re-create.'
    required: false
    default: '${{ github.workspace }}'
  recreate:
    description: 'If the directory should be recreated or not.'
    required: false
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'
